Introduce sorting model for CLEM
APSIMInitiative/ApsimX pull request #6481
Opened 2021-05-20 08:48 UTC by MikeStower

Resolves #6480

2021-05-20 12:56 UTC, lie112 commented
I’ll check the code changes
I’ll also look at why this failed

2021-05-21 00:14 UTC, lie112 commented on Models/CLEM/Activities/RuminantActivityManage.cs
>                              if (herd[cnt] is RuminantFemale)
I believe this is a bug and it should be the herdToSell within the while statement as we don't want to modify the herd, but the individuals in the filtered group to sell

2021-05-21 00:30 UTC, MikeStower commented
> @MikeStower can you address the == issue in labour.cs causing the build failure? Shown in Jenkins error?

I can fix this and standardise the names, since those are quick changes. But I won't have time to make major changes today, focusing on my QAAFI work.

We should be good to retest after those fixes though?

2021-05-21 01:51 UTC, lie112 requested changes
We need to fix the breaking changes and ensure the logic is all correct before merging
The deleted code changes in Labour.cs cause CLEM validation errors and need to be addressed as the model cannot find labour availability for individuals in the cropping example.
We'll have to address these changes on Monday and hopefully I have time to get the new components made Monday night.

2021-05-23 11:11 UTC, MikeStower commented on Models/CLEM/Activities/RuminantActivityManage.cs
>                          {
This shouldn't change the logic at all. The herd is not being modified at any point. The herd is filtered, which generates an independent enumerable. Then, rather than storing that enumerable in a list, we count it immediately.

2021-05-23 11:11 UTC, MikeStower commented on Models/CLEM/Resources/Labour.cs
> +                string msg = $"Unable to find labour availability suitable for labour type {labour.Name} {labour.Gender} {labour.Age}" +
Fixed in 8c309ef

2021-05-23 11:11 UTC, MikeStower commented on Models/CLEM/Resources/Labour.cs
> -                foreach (Model availItem in availabilityList.Children.Where(a => typeof(LabourSpecificationItem).IsAssignableFrom(a.GetType())).ToList())
Fixed in 8c309ef

2021-05-24 04:32 UTC, lie112 commented on Models/CLEM/Activities/RuminantActivityManage.cs
>                          {
It's not really related to this code change. I'll look at it and update it later.  I think it's still a bug in the model logic
I meant that inside the while(cnt < sellNum ...) loop we should be working with herdToSell[cnt] and NOT herd[cnt]

2021-05-24 04:33 UTC, lie112 commented
This is ready to merge @hol353

2021-05-24 04:41 UTC, merged