Full refactor of all CLEM Activities to clean code and remove duplicate code
APSIMInitiative/ApsimX pull request #6724
Opened 2021-08-17 10:06 UTC by lie112

Working on #6692

2021-08-17 21:25 UTC, hol353 requested changes

2021-08-17 21:25 UTC, hol353 commented on Models/CLEM/Activities/ActivityTimerPastureLevel.cs
>          ResourcesHolder Resources = null;
Private fields should start with lowercase

2021-08-17 21:25 UTC, hol353 commented on Models/CLEM/Activities/CropActivityManageCrop.cs
> +
Start with a lowercase letter

2021-08-17 21:25 UTC, hol353 commented on Models/CLEM/Activities/CropActivityManageProduct.cs
And some more privates that start with upper case.

2021-08-17 21:25 UTC, hol353 commented on Models/CLEM/Activities/LabourActivityFeedToTargetsV1.cs
Remove commented code

2021-08-17 21:25 UTC, hol353 commented on Models/CLEM/Activities/PastureActivityCutAndCarry.cs
Another private starting with upper case. Please check all CLEM files for this.

2021-08-17 22:41 UTC, lie112 commented on Models/CLEM/Activities/ActivityTimerPastureLevel.cs
>          ResourcesHolder Resources = null;
How does [Link] work? Does it search for the Type up the tree. I thought SV told be it was searching for a Named component of type and therefore the name had to match. I thought it was odd there were caps elsewhere. I'll add this to my list of things to fix up as I go through the rest of the code.

2021-08-17 22:46 UTC, hol430 commented on Models/CLEM/Activities/ActivityTimerPastureLevel.cs
>          ResourcesHolder Resources = null;
The link attribute has a Type property which determines how it searches for a model. By default, it's set to LinkType.Scoped, so it will search for a model in scope. No matter which link type you use however, the target must always be of a matching (or more derived) type. The name of the property is only used if `ByName` is set to true on the link attribute. So

```csharp
// Resolves to the first model of type ResourcesHolder in the simulations tree (in a depth-first search)
[Link]
// [Link(Type = LinkType.Scoped, ByName = false)] // Equivalent
ResourcesHolder Resources = null;

// Resolves to the first model of type ResourcesHolder in the simulations tree (in a depth-first search)
// which has a name of hello
[Link(ByName = true)] ResourcesHolder hello = null;
```

2021-08-17 23:01 UTC, hol353 commented on Models/CLEM/Activities/ActivityTimerPastureLevel.cs
>          ResourcesHolder Resources = null;
In your second source line I think it is case insensitive so it will find a ResourcesHolder with name hello or Hello.

2021-08-17 23:05 UTC, hol430 commented on Models/CLEM/Activities/ActivityTimerPastureLevel.cs
>          ResourcesHolder Resources = null;
Or hElLo :). I guess this should all probably be documented on the netlify site. In fact there are quite a few comments on github which could probably be useful as a page on that site...

2021-08-18 00:17 UTC, lie112 commented
Seems there's a validation error to do with Tests/Validation/System/FACTS_CornSoy

2021-08-18 00:20 UTC, hol430 commented
There may be similar recurring problems until #6719 is merged...just ping me if you spot it happening again.

retest this please jenkins

2021-08-19 23:06 UTC, lie112 commented
This is ready to go and needed to the next release of improved filtering

2021-08-19 23:11 UTC, hol430 commented on Models/CLEM/Activities/ActivitiesHolder.cs
> +        #region validation
Can the regions be removed?

2021-08-19 23:12 UTC, hol430 commented on Models/CLEM/Activities/ActivitiesHolder.cs
> +        /// Overrides the base class method to allow for clean up
This is kind of minor, but this description seems to be outdated, as this method doesn't override anything. (Also doesn't contain <param> tags for arguments)

2021-08-19 23:14 UTC, hol430 commented on Models/CLEM/Activities/CLEMActivityBase.cs
> +        public ResourcesHolder Resources = null;
This isn't really an issue per se, but why do we need a public link here? We usually try to avoid this elsewhere - usually it's not necessary.

2021-08-19 23:18 UTC, hol430 commented on Models/CLEM/Activities/CropActivityManageProduct.cs
> +        Clock clock = null;
These should be explicitly declared as private.

2021-08-19 23:18 UTC, lie112 commented on Models/CLEM/Activities/ActivitiesHolder.cs
> +        /// Overrides the base class method to allow for clean up
I think this has arisen from very early on and is a 3 year copy and paste error from SV original code. This is likely to be the case for every Subscribed event handler in CLEM. This will be a big job to fix that I don't really have time to do right now. Can I put it on my list of things to do?

2021-08-19 23:18 UTC, lie112 commented on Models/CLEM/Activities/ActivitiesHolder.cs
> +        #region validation
I guess so. I have used these two regions #validation and #descriptive summary throughout CLEM to separate the validation and description logic from the core model. They are more to do with the UI and experience. I didn't realise there was a aversion to #region

2021-08-19 23:20 UTC, lie112 commented on Models/CLEM/Activities/CLEMActivityBase.cs
> +        public ResourcesHolder Resources = null;
This allows one Link here, and all Activities that inherit this base have access to this Model used widely in CLEM. It saves many other [Link] statements being required in every activity Model. I think there are 3 or so cases where this happens in CLEM. Another is the Herd Model that all CLEMRuminantActivityBase classes can see.

2021-08-19 23:21 UTC, hol430 commented on Models/CLEM/Activities/PastureActivityBurn.cs
> +        private GrazeFoodStoreType pasture { get; set; }
These should be fields since they're private.

2021-08-19 23:22 UTC, hol430 commented on Models/CLEM/Activities/PastureActivityCutAndCarry.cs
These should also be declared private explicitly - there are quite a few other instances of this which I've seen while skimming but didn't comment on - they should also be fixed.

2021-08-19 23:22 UTC, hol430 commented on Models/CLEM/Activities/PastureActivityCutAndCarry.cs
> +        private AnimalFoodStoreType foodstore { get; set; }
More private properties which should be fields.

2021-08-19 23:23 UTC, hol430 commented on Models/CLEM/Activities/RuminantActivityControlledMating.cs
> +        /// Provate method to determin resources required for this activity in the current month
Typos?

2021-08-19 23:24 UTC, hol430 commented on Models/CLEM/Activities/RuminantActivityGrazeAll.cs
> +            //ActivityPerformed?.Invoke(sender, e);
Commented code - please remove

2021-08-19 23:25 UTC, hol430 commented on Models/CLEM/Activities/RuminantActivityGrazePasture.cs
> +            //ActivityPerformed?.Invoke(sender, e);
Commented code -please remove

In fact, if this is duplicated from the above class, might be worth thinking about how to reuse, rather than duplicate code, although it's probably beyond the scope of this PR.

2021-08-19 23:28 UTC, hol430 commented on Models/CLEM/FileSQLitePasture.cs
> +        private  Clock clock = null;
Very minor - but this double space should be single

2021-08-19 23:29 UTC, hol430 commented on Models/CLEM/Reporting/ReportQuery.cs
> +                //summary.WriteWarning(this, $"Invalid SQL: Unable to create query report [{this.Name}] using SQL provided\r\nIf your SQL contains links to other ReportQueries you may need to run thi
Commented code - please remove

2021-08-19 23:35 UTC, lie112 commented on Models/CLEM/Activities/RuminantActivityGrazeAll.cs
> +            //ActivityPerformed?.Invoke(sender, e);
I wasn't sure if some big changes here were going to come back and bite me. Gone now

2021-08-19 23:37 UTC, lie112 commented on Models/CLEM/Activities/RuminantActivityGrazePasture.cs
> +            //ActivityPerformed?.Invoke(sender, e);
I realise these two activities use some shared code to create versions of RuminantActivityGrazePastureHerd for running the simulation. It is only in these two Models.

2021-08-19 23:39 UTC, lie112 commented on Models/CLEM/FileSQLitePasture.cs
> +        private  Clock clock = null;
Thanks, I reckon CLEM might now have the cleanest Model code. I would love to use the apply to all in Folder, but it only exists for Document, Project and Solution, which doesn't help me.

2021-08-19 23:39 UTC, hol430 commented on Models/CLEM/Resources/SpecifyRuminant.cs
> +        public bool WeightWarningOccurred = false;
Public - should be a property.

2021-08-19 23:40 UTC, lie112 commented on Models/CLEM/Reporting/ReportQuery.cs
> +                //summary.WriteWarning(this, $"Invalid SQL: Unable to create query report [{this.Name}] using SQL provided\r\nIf your SQL contains links to other ReportQueries you may need to run thi
This line will be reinstated when @hol430 fixes the datastore error bubbling and allows immediate Summary message writing. I don't want an error here, but report to summary so all similar errors are reported rather than stopping here.

2021-08-19 23:41 UTC, hol430 commented on Models/CLEM/Resources/WaterType.cs
> +        private double amount { get { return roundedAmount; } set { roundedAmount = Math.Round(value, 9); } }
If private - should be a field. If you need the rounding logic, perhaps change that to a method.

2021-08-19 23:43 UTC, hol430 commented on Models/CLEM/Activities/ActivitiesHolder.cs
> +        #region validation
https://apsimnextgeneration.netlify.app/development/software/codingstyle/#region-usage

2021-08-19 23:44 UTC, hol430 commented on Models/CLEM/Activities/ActivitiesHolder.cs
> +        /// Overrides the base class method to allow for clean up
Feel free.

2021-08-19 23:46 UTC, hol430 commented on Models/CLEM/Activities/CLEMActivityBase.cs
> +        public ResourcesHolder Resources = null;
Perhaps make it protected then, if it's only accessed from derived types?

2021-08-19 23:49 UTC, hol430 commented on Models/CLEM/Reporting/ReportQuery.cs
> +                //summary.WriteWarning(this, $"Invalid SQL: Unable to create query report [{this.Name}] using SQL provided\r\nIf your SQL contains links to other ReportQueries you may need to run thi
Makes sense - perhaps add a comment to that effect?

2021-08-20 00:03 UTC, lie112 commented on Models/CLEM/Activities/ActivitiesHolder.cs
> +        /// Overrides the base class method to allow for clean up
I think it came from the original copy of the Method in Clock.OnSimulationCommencing

2021-08-20 00:15 UTC, lie112 commented
I assume the .vs folder is not part of the repo. I had to delete my .vs folder to fix issues with Visual Studio. Now it wants to commit the deletes. Can I add ignore .vs folder to the Git checklist? Is that a shared file, or local to my Git repo?

2021-08-20 00:19 UTC, hol430 commented
The .vs directory shouldn't be part of the repo, although someone must have committed some files inside it at some stage. To undo any local changes so that they don't show up in sourcetree, you should be able to delete the .vs directory from your computer, then go to sourcetree and those files will show up as deleted. I think you can right click them and choose "discard" (or similar), and you should see that the .vs directory exists once more (and sourcetree will show no changes).

2021-08-20 01:00 UTC, lie112 commented on Models/CLEM/Activities/ActivitiesHolder.cs
> +        #region validation
Yeah, I know. What about all the other models in APSIM (Utilities, ApsimNG, Pasture, Aqua, Functions, GRange.......) all using # region? Just do a quick find all. It's widely used so I thought it was accepted. Happy for them to go when you do a remove all from Solution.

2021-08-20 03:21 UTC, lie112 commented
Hmm, error to be addressed by @hol430 .

2021-08-20 03:22 UTC, hol430 commented
retest this please jenkins

2021-08-22 22:42 UTC, hol430 approved these changes
@hol353 I think this is good to merge. This PR makes the clem code much more compliant with the code standards.

2021-08-22 23:03 UTC, hol353 approved these changes

2021-08-22 23:03 UTC, merged