Change perennial leaf to maintain a running total of live/dead biomass
APSIMInitiative/ApsimX pull request #6754
Opened 2021-08-30 05:15 UTC by hol430

...in order to avoid re-calculating these every time the Live or Dead property is accessed.

Working on #6753.

2021-08-31 05:12 UTC, hol430 commented
@hol353 - I don't think that using SleepJobs instead of EmptyJobs is going to work. Can discuss this with you tomorrow, but basically the post-simulation tools are only run if `InvokeJobCompleted` is called. If the last job that gets run happens to be a sleep job, the post-simulation tools don't get run  (this occurs in one of our unit tests, and also when you refresh the datastore in the gui). The other problem is that NumJobsComplete is incorrect when using SleepJobs, as it doesn't get incremented. This is easier to solve, but does require us to acquire an extra lock.

I think we will need to find another approach to this issue.

2021-08-31 21:27 UTC, hol353 commented
Hmmm this is too messy. We shouldn't have either SleepJob or EmptyJob. Both are hacks. Time for a redesign of the JobRunner?

2021-09-06 02:04 UTC, hol430 commented
@hol353 this is now green and could probably be merged. Do we want to close the underlying issue, or were there more problems you wanted to address?

2021-09-06 03:19 UTC, hol353 requested changes

2021-09-06 03:19 UTC, hol353 commented on APSIM.Shared/JobRunning/JobRunner.cs
> +                        var startTime = DateTime.Now;
What is this? Surely it isn't needed.

2021-09-06 03:19 UTC, hol353 commented on Prototypes/Canola/Canola.apsimx
>                ],
Why has canola.apsimx changed? Why has nodule been removed?

2021-09-06 03:20 UTC, hol353 commented
Let's close the underlying issue once this is merged. Can you also create a new issue to rethink how a JobRunner is kept 'awake'. In other words can we get rid of EmptyJob and SleepJob?

2021-09-06 03:22 UTC, hol430 commented on APSIM.Shared/JobRunning/JobRunner.cs
> +                        var startTime = DateTime.Now;
I think I added a few lines into this lock but that change has been partially reverted somewhere along the line. I'll revert this particular hunk as well.

2021-09-06 03:22 UTC, hol430 commented on Prototypes/Canola/Canola.apsimx
>                ],
Canola doesn't have a nodule. Previously these were being ignored. With the new biomass they cause errors.

2021-09-06 03:54 UTC, hol353 approved these changes

2021-09-06 03:54 UTC, merged