Implement CLEM filtering and sorting of individuals
APSIMInitiative/ApsimX pull request #6784
Opened 2021-09-08 04:41 UTC by lie112

resolves #6692 

Implements the new filter and sort of individuals, both with full generic reflection and a a faster hard coded method for large herds
Cleans up the remainder of CLEM code
Fixes bugs identified from previous refactoring around generic resource location and economic reporting

2021-09-12 23:14 UTC, lie112 commented
I realise this is a bit to go through, but can I get this into an upgrade soon
There shouldn't been too many code issues like wayward commented code.

2021-09-13 00:24 UTC, hol430 requested changes

2021-09-13 00:24 UTC, hol430 commented on Models/CLEM/Groupings/FilterByProperty.cs
> +                    //var simpleCompareVal = Expression.Constant(Convert.ChangeType(Value ?? 0, propertyInfo.PropertyType.IsEnum? typeof(string): propertyInfo.PropertyType));
Commented code

2021-09-13 00:24 UTC, hol430 commented on Models/CLEM/Groupings/FilterByProperty.cs
> +        private string filterString(bool htmltags)
Function name should start with upper case letter.

2021-09-13 00:24 UTC, hol430 commented on Models/CLEM/Groupings/OtherAnimalsFilterGroup.cs
> +    //[Description("Selects specific individuals from the other animals")]
Commented code - could be removed

2021-09-13 00:24 UTC, hol430 commented on Models/CLEM/Groupings/SortByProperty.cs
> +        private string sortString(bool htmltags)
Function name should start with upper case letter.

2021-09-13 00:24 UTC, hol430 commented on Models/CLEM/Groupings/TakeFromFiltered.cs
> +        private string takeString(bool htmltags)
Function name should start with upper case letter.

2021-09-13 00:24 UTC, hol430 commented on Models/CLEM/Resources/CLEMResourceTypeBase.cs
> +                //case WaterType _:
Commented code - please remove if not needed

2021-09-13 00:24 UTC, hol430 commented on Models/CLEM/Resources/IndividualAttribute.cs
> +                if(float.TryParse(StoredValue.ToString(), out float val))
Probably  best to explicitly specify the culture rules when parsing numbers from strings like this. Using the invariant culture is usually best, otherwise your simulations can give different results depending on the language/locale settings of the computer on which they're run - e.g. some cultural settings use commas for decimal place separators and periods for thousands separators.

2021-09-13 00:24 UTC, hol430 commented on Models/CLEM/Resources/IndividualAttribute.cs
> +                if (float.TryParse(StoredMateValue.ToString(), out float val))
See above comment re cultural settings

2021-09-13 00:24 UTC, hol430 commented on Models/CLEM/Resources/Labour.cs
> +                    string warningString = "No [Pay] rate entry was found meeting the required criteria [" + property.Name + "]" + (value.ToUpper() != "TRUE" ? " = [" + value + "]." : ".");
Usually best to avoid lots of string concatenation like this as it can result in a lot of allocations, especially if this is called daily (or multiple times per day). This isn't really a huge issue - but usually it's preferable (and more readable!) to use string interpolation or a StringBuilder.

2021-09-13 00:24 UTC, hol430 commented on Models/CLEM/Resources/Ruminant.cs
> +        public Sex Sex { get { return ((this is RuminantMale) ? Sex.Male : Sex.Female); } set {  } }
What's the idea behind the empty setter? Is this required by an interface? Would it be better/feasible to throw a not implemented exception?

In fact, looking closer, I see that this is an abstract class. If this property comes from an interface, perhaps it would be better to implement this property only in the concrete types derived from this abstract class - I'm guessing `RuminantMale` and `RuminantFemale`?

2021-09-13 00:24 UTC, hol430 commented on Models/CLEM/Resources/SetAttributeWithValue.cs
> +            if (createNewInstance | lastInstance is null)
Bitwise OR - probably a typo?

2021-09-13 00:24 UTC, hol430 commented on Models/CLEM/ZoneCLEM.cs
> +//                    htmlWriter.Write(CLEMModel.AddMemosToSummary(this));
Commented code

2021-09-13 00:57 UTC, lie112 commented on ApsimNG/Presenters/CLEM/CLEMPresenter.cs
> +using Models.CLEM.Interfaces;
This is needed for ICLEMUI on line 19, 38. It is not greyed out in my code. Shall I remove all unused usings from other models and presenters etc?

2021-09-13 01:00 UTC, lie112 commented on ApsimNG/Presenters/CLEM/CLEMReportResultsPresenter.cs
> +                    report = (clemPresenter.model as Model).FindChild<Report>();
The clemPresenter.model is an object. report is a private local variable only used in this method. It is the same as in ReportPresenter to identify simulations, simulation, experiment and paddock for the datastorePresenter.ZoneFilter

2021-09-13 01:01 UTC, hol430 commented on ApsimNG/Presenters/CLEM/CLEMPresenter.cs
> +using Models.CLEM.Interfaces;
I wouldn't bother going out of your way to fix existing ones - I usually just give them a quick glance whenever I add or remove one while working on a class.

2021-09-13 01:12 UTC, lie112 commented on Examples/CLEM/CurrentDescriptiveSummary.html
> +<!DOCTYPE html>
Yes. These are annoying. I have updated my GitIgnore file to include these, but it doesn't seem to pick them up and ignore them. I didn't use **/ but just the filename as Git doco said a filename alone will be ignored anywhere in the source code.

2021-09-13 01:14 UTC, lie112 commented on Models/CLEM/Activities/PastureActivityManage.cs
> +                    //SetupStartingPasturePools(StartingAmount);
yeah, missed all those. It was the last thing I was working on

2021-09-13 01:30 UTC, lie112 commented on Models/CLEM/Activities/RuminantActivityFeed.cs
> +                if(feedRequest == null || (feedRequest.Required == 0 | feedRequest.Available == 0) || feedLimit <= 0.00001)
Yes, thanks. That was mentioned in last weeks APSIM catch-up. I was confused with previous && to avoid moving on if feedrequest was null. Solved with feedRequest?.Required

2021-09-13 01:35 UTC, lie112 commented on Models/CLEM/Groupings/OtherAnimalsFilterGroup.cs
> +    //[Description("Selects specific individuals from the other animals")]
This was work in progress relating to another problem.

2021-09-13 01:56 UTC, lie112 commented on Models/CLEM/Resources/Ruminant.cs
> +        public Sex Sex { get { return ((this is RuminantMale) ? Sex.Male : Sex.Female); } set {  } }
We actually had this implemented the way you suggest, but it won't work with Report. If a user wants to report Individual.Sex (where individual is type Ruminant), Report will set the PropertyInfo for this based on the first individual applied to (e.g. Female, RumiantFemale.Sex), then when report tries to report Sex for a Male later in the reporting an exception is thrown as RuminantFemale.Sex PropertyInfo cannot be found  on male. I think the null set was to get this working as it didn't seem to pick up get only properties in Report. I thought about a fix for report but couldn't come up with a generic solution for this specific issue. In the end implementing Sex for Ruminant was the easiest fix.

2021-09-13 02:59 UTC, hol430 commented on ApsimNG/Presenters/CLEM/CLEMReportResultsPresenter.cs
> +                    report = (clemPresenter.model as Model).FindChild<Report>();
Ok - clemPresenter.model should have an uppercase M (so clemPresenter.Model). I would probably be inclined to change its type at least to IModel, or possibly something more derived if you think that would make more sense. I can't think of a situation where the model passed into the presenter isn't an IModel - in fact, the `Attach()` method's definition in `IPresenter` should really have an IModel, rather than an object, for the model property...but I digress. Feel free to change this one or leave it, whatever you think makes sense.

2021-09-13 05:17 UTC, lie112 commented on Models/CLEM/Resources/SetAttributeWithValue.cs
> +            if (createNewInstance | lastInstance is null)
Ors still do my head in a bit. It really doesn't matter in this case does it? It doesn't matter if both are evaluated, but might be a smidgen quicker if we didn't need to evaluate the null check.

2021-09-13 06:18 UTC, lie112 commented on Models/CLEM/Resources/Ruminant.cs
> +        public Sex Sex { get { return ((this is RuminantMale) ? Sex.Male : Sex.Female); } set {  } }
I had a large reply for this but it never sent. We originally had the classes working as you suggested. The only problem is Reports don't like it. The way you suggest, if you want to report on Sex of a ruminant in a report the PropertyInfo is taken from the first individual in the list (which may be a Female, so PI is RuminantFemale.Sex), then later when it tries to report on a ruminant male if cannot find the property (RuminantFemale.Sex) on the object (RuminantMale) and throws a fatal error. I looked into ways to resolve this but it got quite messy and I figured the current implementation was the easiest for a single situation and we didn't want reflection calls at every write to the report which is already a intesnive part of the model. In trying to resolve the issue I thought the Report was not accepting {get; } only properties so I added the empty set {} and it started working, but it may have been related to something else and so might be able to be deleted. I thought I'd come across this before so tried my same old approach to fix it and keep exploring options.

2021-09-13 22:57 UTC, lie112 commented on ApsimNG/Presenters/CLEM/CLEMReportResultsPresenter.cs
> +                    report = (clemPresenter.model as Model).FindChild<Report>();
This is a hangover from using the private variables already defined by APSIM in most of the presenters and needing to access it without changing its name. I missed that my internals were actually public. Their types was a carryover from propertypresenter 
line 53 PropertyPresenter,cs        public virtual void Attach(object model, object view, ExplorerPresenter explorerPresenter)
I have changed my internal objects for CLEM presenter  to capital letters. This may be the case elsewhere

2021-09-13 23:26 UTC, lie112 commented on Models/CLEM/Resources/Ruminant.cs
> +        public Sex Sex { get { return ((this is RuminantMale) ? Sex.Male : Sex.Female); } set {  } }
I would like to fix this while cleaning this all up. I don't like the type check (is RuminantMale) every time we access Sex (a common call). I could have a localised version on each inherited type that returns the enum value back to the general base property. Am I missing something fundamental in inheritance here? I'm not sure if the problem was the abstract class not allowing me to assign a property for the report, or just the fact that it asked for the property info from the RuminantFemale as the first object not from the female's base Ruminant class that would have worked for both males and females. Unless the base property is not valid. Any ideas here?

2021-09-13 23:43 UTC, lie112 commented on Models/CLEM/Resources/Ruminant.cs
> +        public Sex Sex { get { return ((this is RuminantMale) ? Sex.Male : Sex.Female); } set {  } }
It worked today. Must have just been some fresh coding.

2021-09-13 23:48 UTC, hol430 commented on Models/CLEM/Resources/Ruminant.cs
> +        public Sex Sex { get { return ((this is RuminantMale) ? Sex.Male : Sex.Female); } set {  } }
This works in simple cases, but I've found the bug you mentioned. It happens when the property we're reporting is of the abstract class' type. As you said, it's caching the PropertyInfo of the concrete type which leads to an exception if the value of the property (containing an instance of the abstract type) changes.

2021-09-14 00:09 UTC, hol430 commented on Models/CLEM/Resources/Ruminant.cs
> +        public Sex Sex { get { return ((this is RuminantMale) ? Sex.Male : Sex.Female); } set {  } }
This is fixed by #6795.

2021-09-14 00:12 UTC, lie112 commented on Models/CLEM/Resources/Ruminant.cs
> +        public Sex Sex { get { return ((this is RuminantMale) ? Sex.Male : Sex.Female); } set {  } }
ok. It all looked good but the example I was working with only had females so didn't introduce the issue.
The problem is visible in the current Jenkins build when it tries to use the clem grazing example where there are males and females. I would have thought this was using the #6795 fix, but isn't working.

2021-09-14 00:13 UTC, hol430 commented on Models/CLEM/Resources/Ruminant.cs
> +        public virtual Sex Sex { get { return this.Sex; } }
```suggestion
        public abstract Sex Sex { get; }
```

Then in the derived types:

```csharp
public override Sex Sex { get { return ... } }
```

2021-09-14 00:16 UTC, hol430 commented on Models/CLEM/Resources/Ruminant.cs
> +        public Sex Sex { get { return ((this is RuminantMale) ? Sex.Male : Sex.Female); } set {  } }
Well, this jenkins build ran half an hour ago, whereas I only created #6795 a few minutes ago...we haven't implement a time travel feature in jenkins yet :).

Once #6795 is merged, we can retest this and it should (hopefully) run green. I'm just hoping I haven't  broken anything with #6795...

2021-09-14 00:19 UTC, lie112 commented on Models/CLEM/Resources/Ruminant.cs
> +        public Sex Sex { get { return ((this is RuminantMale) ? Sex.Male : Sex.Female); } set {  } }
How do you implement this. I have tried a public virtual and abstract on the base Ruminant with the inherited models providing a new Sex Sex { get { return Sex.Male }} etc. But I still get an error in Report. 
Invalid report variables found: Sex: Object does not match target type.

2021-09-14 00:20 UTC, lie112 commented on Models/CLEM/Resources/Ruminant.cs
> +        public Sex Sex { get { return ((this is RuminantMale) ? Sex.Male : Sex.Female); } set {  } }
oops, should be override?

2021-09-14 00:22 UTC, hol430 commented on Models/CLEM/Resources/Ruminant.cs
> +        public Sex Sex { get { return ((this is RuminantMale) ? Sex.Male : Sex.Female); } set {  } }
Yep, you will want abstract in the base class (Ruminant), and override in the derived class (RuminantMale/Female). The "object does not match target type" error should be fixed by #6795.

2021-09-14 00:51 UTC, lie112 commented on Models/CLEM/Resources/Ruminant.cs
> +        public Sex Sex { get { return ((this is RuminantMale) ? Sex.Male : Sex.Female); } set {  } }
I should have checked the date of #6795, I assumed it was already included. I'll await it to be accepted and try again.

2021-09-14 23:30 UTC, lie112 commented
This is right to go. Just need to retest jenkins after #6797 merges as I am awaiting that Reports fix.

2021-09-16 00:47 UTC, lie112 commented
@hol430 @hol353 Can I please get the outstanding #6795 merged so I can re-run Jenkins to allow this pull request to be included and an upgrade created. I have a number of users awaiting this upgrade for projects.

2021-09-16 04:01 UTC, hol430 commented
@hol353 - see above. I think if you're happy with #6795 it could be merged, then we can get this PR going again.

2021-09-16 04:55 UTC, hol430 commented
retest this please jenkins

2021-09-17 00:31 UTC, hol430 approved these changes
Looks good to me.

2021-09-17 00:31 UTC, merged

2021-09-17 01:13 UTC, lie112 commented
@hol430 seems the last upgrade was 7/9 --6775 
Should I be able to see the master branch including our latest changes? SourceTree has masterbranch sitting at this previous CO2 not read from met file merge, but git repo online says master is at our latest merge. What am I missing?

2021-09-17 01:42 UTC, hol430 commented
Well, it depends on which master branch you're referring to. There's a master branch on this remote repository, there's a master branch on your forked repository, and there's also (presumably) a local master branch sitting on your computer. The master branch on this repo definitely contains the changes in this PR - if it's not showing that in sourcetree, try doing a fetch (of this repository). If the problem is with the local master branch on your computer, you can checkout that branch, then do a pull from this repo's master branch. If the problem is with the master branch on your forked repository, you'll need to perform the previous step to bring your local master branch up to date, and then push up to the master branch on your forked repo.

[This page](https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches) has some background info and diagrams which may be more helpful than my explanation.

2021-09-17 01:53 UTC, lie112 commented
I was looking at releasefork/master on the apsimx repo but couldn't get a refresh.
I restarted SourceTree and all is is good. The usual refresh wasn't working.
Time to ditch sourcetree I think. What are you using for source control?...command line I assume!

Is the update generator currently working? The last upgrade is 2021.09.07.6675
Did you once give me a link to see the latest progress on upgrade.
I have the jenkins progress link which I use a lot.

2021-09-17 02:06 UTC, hol430 commented
Yeah, I tried a few git guis but had (minor-ish) problems with all of the ones I tried, so I just use the command-line git these days.

Upgrades seem to be broken...again...I'm hoping that the problem fixed by #6803 is the only problem. If so, we may see a new upgrade later today.

You can see jenkins building upgrades by going to the [jenkins homepage](http://apsimdev.apsim.info:8080/jenkins/) and clicking on the CreateInstallation job. Or I suppose you could just use [this link](http://apsimdev.apsim.info:8080/jenkins/job/CreateInstallation/) and cut out the middle man, so to speak.