Implement padding to property and markdown presenter
APSIMInitiative/ApsimX pull request #6897
Opened 2021-10-29 06:46 UTC by lie112

Resolves #6896

2021-10-31 23:59 UTC, hol353 requested changes

2021-10-31 23:59 UTC, hol353 commented on ApsimNG/Views/CLEM/CLEMView.cs
> +                //}
Please remove the commented code.

2021-10-31 23:59 UTC, hol353 commented on ApsimNG/Views/CLEM/ModelDetailsWrapperView.cs
>          private Viewport bottomView = null;
More commented code.

2021-10-31 23:59 UTC, hol353 commented on ApsimNG/Views/CLEM/ModelDetailsWrapperView.cs
>              scroll.SetPolicy(PolicyType.Automatic, PolicyType.Automatic);
commented code.

2021-11-01 09:12 UTC, lie112 commented
Too easy to miss cleaning up commented code during development.

2021-11-01 21:20 UTC, hol353 approved these changes

2021-11-01 21:20 UTC, merged