worldmodel url wants "." instead of ","
APSIMInitiative/ApsimX pull request #6899
Opened 2021-10-30 11:31 UTC by dexy58

resolves url when using NASA POWER w/ CHIRPS rainfall (World Modellers)

2021-10-31 22:24 UTC, hol430 requested changes

2021-10-31 22:24 UTC, hol430 commented on ApsimNG/Utility/WeatherDownloadDialog.cs
> +            entryLatitude.Text = entryLatitude.Text.Replace(',', '.');
Instead of doing a straight text replace here, I think it will be better to 

1. Convert the lat/long input strings to doubles (using the current culture) - this will account for things like ',' as decimal separator or '.' as thousands separator as may be the case on the user's system
2. Convert these parsed doubles back to strings (using the invariant culture) - this will generate a string in the american format (ie using '.' for decimal separator), which should be safe to pass into the API

ie something like this:

```csharp
double latitude = double.Parse(entryLatitude.Text, CultureInfo.CurrentCulture);
double longitude = double.Parse(entryLongitude.Text, CultureInfo.CurrentCulture);

string latitudeStr = latitude.ToString(CultureInfo.InvariantCulture);
string longitudeStr = longitude.ToString(CultureInfo.InvariantCulture);
// (and then use latitudeStr/longitudeStr as parameters to the climate API)
```

2021-11-02 08:12 UTC, dexy58 commented on ApsimNG/Utility/WeatherDownloadDialog.cs
> +            entryLatitude.Text = entryLatitude.Text.Replace(',', '.');
Hello :)

Do I have to commit this to the patch-1 branch on dexy58/ApsimX to make the change? I have never done this (this is the 1st time I am contributing to the open source project, so I don't know the procedure).
Thanks.

2021-11-02 19:27 UTC, dexy58 commented on ApsimNG/Utility/WeatherDownloadDialog.cs
> +            entryLatitude.Text = entryLatitude.Text.Replace(',', '.');
Okay, I commited the changes in patch-1 branch on dexy58/ApsimX and it seems it has done the trick. It works, but I had to change a few other things because of those changes. Check them if you think we should revert it.

2021-11-02 22:57 UTC, hol430 commented
retest this please jenkins

2021-11-02 23:53 UTC, hol430 approved these changes
Looks good - thanks for the contribution @dexy58!

2021-11-02 23:53 UTC, merged