Forages
APSIMInitiative/ApsimX pull request #6939
Opened 2021-11-10 21:13 UTC by hol353

Resolves #6258.

Don't merge yet!!!

2021-11-12 01:21 UTC, hol353 commented
@hol430 I'm ok with the minor stats changes. This is ready for review / merge.

2021-11-12 01:50 UTC, hol430 requested changes

2021-11-12 01:50 UTC, hol430 commented on Models/AgPasture/PastureAboveGroundOrgan.cs
> +            //biomassToRemove.FractionLiveToRemove = MathUtilities.Divide(biomassToRemove.FractionLiveToRemove * DMLiveHarvestable, DMLive, 0);
Is this still needed? If not, can it be removed?

2021-11-12 01:50 UTC, hol430 commented on Models/AgPasture/SimpleGrazing.cs
> +            if (clock.Today == new DateTime(1995, 7, 8))
Debug code

2021-11-12 01:50 UTC, hol430 commented on Models/AgPasture/SimpleGrazing.cs
> +                        throw new Exception($"Model {(forage as IModel).Name} is unable to reduce its population due to grazing. Not implemented.");
Cast to IModel shouldn't be necessary, right? In fact how does this even work? I'm assuming that forage is a ModelWithDigestibleBiomass (I don't actually know because of the var keyword above...). ModelWithDigestibleBiomass doesn't implement IModel from what I can see so I would expect this to throw...

2021-11-12 01:50 UTC, hol430 commented on Models/ForageDigestibility/ModelWithDigestibleBiomass.cs
> +            public DigestibleBiomass Material;
These should probably be properties (even though it's a private class). Might as well be explicit about the accessibility...

2021-11-12 01:50 UTC, hol430 commented on Models/PMF/Interfaces/IHasDamageableBiomass.cs
> +    public class DamageableBiomass
Can this class be moved into its own file? They can be hard to track down otherwise - and this class isn't even related to the interface mentioned by the file name.

2021-11-14 21:56 UTC, hol353 commented on Models/AgPasture/SimpleGrazing.cs
> +                        throw new Exception($"Model {(forage as IModel).Name} is unable to reduce its population due to grazing. Not implemented.");
Good catch. Yes the throw would have thrown (sounds weird).

2021-11-14 22:30 UTC, hol430 approved these changes

2021-11-14 22:31 UTC, merged