Added CLI run functionality for apsim.dll
APSIMInitiative/ApsimX pull request #6988
Opened 2021-12-04 17:28 UTC by dexy58

Fixed [#6987 ]( https://github.com/APSIMInitiative/ApsimX/issues/6987)

2021-12-04 18:18 UTC, dexy58 commented
@hol430 Hello, can you please check why TestSendDataTable test fails? I can't seem to figure it out (I haven't even touched any of the methods this Test calls.

2021-12-05 23:45 UTC, hol430 commented
Maybe a race condition in the test...

retest this please jenkins

2021-12-06 08:49 UTC, dexy58 commented
@hol430 Thank you :)
All tests have passed now.

2021-12-07 01:27 UTC, hol430 requested changes
Thanks for the contribution, @dexy58!

2021-12-07 01:27 UTC, hol430 commented on APSIM.Cli/Program.cs
> +                }
I don't think we need to resolve links for .json files here. I think we only do that in the `Document()` function as a bit of a hack, but it shouldn't be necessary for running files - only for documenting them.

```suggestion
```

2021-12-07 16:23 UTC, dexy58 commented on APSIM.Cli/Program.cs
> +                }
Commited this change. Tested it and it works without this part.

2021-12-08 01:57 UTC, hol430 approved these changes

2021-12-08 01:57 UTC, merged