Simple organ arbitrator
APSIMInitiative/ApsimX pull request #7462
Opened 2022-08-25 01:40 UTC by HamishBrownPFR

working on #6763

2022-08-26 00:54 UTC, HamishBrownPFR commented
@hol353 there seems to be a problem with pull requests hanging?

2022-08-26 01:16 UTC, hol353 commented
I've aborted your PR on Jenkins. Will be interesting to see whether the next few PRs run. Not sure why this one failed.

2022-08-26 02:31 UTC, HamishBrownPFR commented
retest this please jenkins

2022-08-26 03:28 UTC, HamishBrownPFR commented
@hol353 pretty sure it has jammed again

2022-08-26 03:49 UTC, hol353 commented
Yep. I don't have time this afternoon. Will have to wait until Monday.

2022-08-26 04:04 UTC, HamishBrownPFR commented
OK, thanks @hol353

2022-08-29 04:52 UTC, HamishBrownPFR commented
retest this please jenkins

2022-08-30 02:54 UTC, HamishBrownPFR commented
@hol353 can you check this and merge if you are happy.

2022-08-30 02:58 UTC, jbrider reviewed
What is causing the changes to the memo text - hyphens and degree symbols are being changed?

2022-08-30 03:03 UTC, HamishBrownPFR commented
Not sure, I just ran the converter.

2022-08-30 03:10 UTC, HamishBrownPFR commented
Have fixed manually and pushed up

2022-08-30 03:18 UTC, jbrider commented
I was sure you hadn't touched it Hamish - I'm more concerned it will keep happening every time the converter is run (assuming that was the cause).

2022-08-30 03:41 UTC, HamishBrownPFR commented
The converter didn't seem to affect the memos in the other Json files though.  So I wonder if it was something I did.  I converted all the other files seperately, then pulled down the sorgham.json file from your commit and ran the converter from the UI again.  My hope was that would just find the files that had not been converted and do them.  It seemed to work but the sorgham has been treated differently.

2022-08-30 21:36 UTC, hol353 requested changes
Seems to be a lot of new code here. Does this PR introduce a new organ arbitrator or is it a refactor of the existing one? I suspect the later. If so, is this the first of many iterative changes to the arbitrator? At one point you were proposing a brand new organ arbitrator. Is that still the case?

2022-08-30 21:36 UTC, hol353 commented on Models/Functions/RootShape/RootShapeCylinder.cs
>          {
Really? Instead of 'IStuffForRootShapeThing' how about 'IRootShape'

2022-08-30 21:36 UTC, hol353 commented on Models/PMF/BiomassArbitration/EnergyBalance.cs
> +        private void allocationMade()
All method names should start with upper case letter.

2022-08-30 21:36 UTC, hol353 commented on Models/PMF/BiomassArbitration/Functions/PlantPartitionFractions.cs
> +        public IEnumerable<IFunction> ChildFunctions;
Should be a property not a field. Add {get; set;} on the end of the declaration.

2022-08-30 21:36 UTC, hol353 commented on Models/PMF/BiomassArbitration/Functions/PlantPartitionFractions.cs
> +
Same with this one. Make it: public Dictionary<string, double> PartitionFractions {get; set; } = new Dictionary<string, double>();

2022-08-30 21:36 UTC, hol353 commented on Models/PMF/BiomassArbitration/Structures/NutrientPoolsState.cs
> +    }
Put the interface into a separate file.

2022-08-30 21:36 UTC, hol353 commented on Models/PMF/BiomassArbitration/Structures/NutrientPoolsState.cs
> +        /// <summary>Gets or sets the structural.</summary>
This class looks similar to the Biomass class. Can't use the Biomass class?

2022-08-30 21:36 UTC, hol353 commented on Models/PMF/BiomassArbitration/Structures/UIStructures.cs
> +
Why are the links public? Normally they should be private.

2022-08-30 21:36 UTC, hol353 commented on Models/PMF/BiomassArbitration/Structures/UIStructures.cs
> +    {
Separate files for each class please.

2022-08-30 21:36 UTC, hol353 commented on Models/PMF/Interfaces/IRoot.cs
> +    {
yep funny but change to IRoot. Separate file for the interface as well. I can't remember if we already have an IRoot. If we do then can we just use that?

2022-08-30 21:36 UTC, hol353 commented on Models/PMF/Organs/RootZoneState.cs
> +
Separate file for interface.

2022-08-30 21:36 UTC, hol353 commented on Models/PMF/Organs/RootZoneState.cs
This probably isn't needed because you're inheriting from Model. Why is ZoneState now a Model?

2022-08-30 23:36 UTC, HamishBrownPFR commented
>

2022-08-30 23:39 UTC, HamishBrownPFR commented
@hol353 It is a new organ arbitrator and new organ class as well.  Enables all organs to be represented by the same organ class with root and leaf specific functionality added in child classes.
I will review each of your comments above and action/respond

2022-08-31 03:58 UTC, HamishBrownPFR commented on Models/Functions/RootShape/RootShapeCylinder.cs
>          {
Changed as requested

2022-08-31 04:05 UTC, HamishBrownPFR commented on Models/Functions/RootShape/RootShapeCylinder.cs
>          {
Actually Not, IRootShape is all ready used by the different root shape objects.

2022-08-31 04:33 UTC, HamishBrownPFR commented on Models/Functions/RootShape/RootShapeCylinder.cs
>          {
IStuffForRootShapeThing holds the bits that IRootShape classes need from RootZoneState or NetworkZoneState.  Kind of hard to think of a good name.  I have changed to IRootGeometryData.  Let me know if this is not OK

2022-08-31 04:38 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/EnergyBalance.cs
> +        private void allocationMade()
changed

2022-08-31 04:42 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Functions/PlantPartitionFractions.cs
> +        public IEnumerable<IFunction> ChildFunctions;
done

2022-08-31 04:43 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Functions/PlantPartitionFractions.cs
> +
Done

2022-08-31 04:47 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Structures/NutrientPoolsState.cs
> +    }
Done

2022-08-31 04:52 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Structures/UIStructures.cs
> +
In this case NutrientPoolFunctions is being used as a container for the GUI to group functions representing biomass pools and the function value is accessed by the parent class so the need to be kept public.  Is there a better way of doing this?.

2022-08-31 21:43 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Structures/UIStructures.cs
> +    {
Done

2022-08-31 21:50 UTC, HamishBrownPFR commented on Models/PMF/Interfaces/IRoot.cs
> +    {
Have deleted this now as was not used.  Must have a temporary step that I forgot to remove.  Which is why I gave it a name that would draw attention.

2022-08-31 21:53 UTC, HamishBrownPFR commented on Models/PMF/Organs/RootZoneState.cs
> +
Done

2022-08-31 23:57 UTC, HamishBrownPFR commented
Hi @hol353 I have responded to each or your comments and committed the changes requested.  Can you check and let me know if there is anything further.  Many thanks

2022-09-01 00:18 UTC, hol353 commented on Models/PMF/BiomassArbitration/Structures/UIStructures.cs
> +
I don't know what this means. Can't a 'folder' group child functions?

2022-09-01 00:22 UTC, hol353 commented on Models/PMF/Organs/RootZoneState.cs
A class doesn't need to inherit from Model to implement an interface. You only need to make something a Model if it will be linked to from another model or you want to see it in the GUI. Would this work:

```c#
public class ZoneState: IStuffForRootShapeThing
```

BTW: need a better name than IStuffForRootShapeThing

2022-09-01 00:27 UTC, hol353 commented on Models/PMF/BiomassArbitration/Organ.cs
> +    {
We now have an Organ class that doesn't implement IOrgan?

2022-09-01 00:45 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Organ.cs
> +    {
@hol353 Thats right.  IOrgan only has two properties, RemoveBiomass and  maintenanceRespiration.  I haven't got to biomass removal yet for the new organ and did not want to implement maintenance respiration so have left the IOrgan interface off for the time being.  I will need to revisit this.

2022-09-01 02:10 UTC, HamishBrownPFR commented
@hol353 I understand your discomfort.  However, I am not sure how else we can implement a tidier approach to doing arbitration without introducing this extra code.  I tried making smaller modifications to the existing code but kept running into problems.  To put it into perspective, the 4000 lines of code here could replace nearly all the classes in the Arbitrator, Biomass and Organs folders in PMF.  I am not sure how to work out how many lines of code that is.  
I am keep to try to set up a few different models in this structure to see how it works and what the issues are.  I could keep it out on a branch while doing that.   Not so keen on that.  Is there anything I can do to reduce the maintenance burden of this in the mean time?  For example, remove autodoc methods so autodoc maintenance is not concerned by the extra files added?

2022-09-01 05:00 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Structures/UIStructures.cs
> +
![image](https://user-images.githubusercontent.com/7295858/187833021-ad5b3412-6300-4046-92b0-b7def7e7f926.png)
It looks like this in the UI.  ReTranslocation is a NutrientPoolFunctions type with Structural, Metabolic and Storage functions as children.  I don't think I could use a folder in place of the NutrientPoolfunctions type for ReTranslocation (in this example) because the SupplyFunctions parent (which is of type NutrientSupplyFunctions) needs to link to a model of type NutrientSupplyFunctions.  
![image](https://user-images.githubusercontent.com/7295858/187834076-e4a2c26b-fcc6-43b2-acaf-8e1c1072f231.png)
I could try replacing the NutrientPoolFunctions type with a folder and see if I can get that to work.  The NutrientPoolFunctions type is being used by the existing arbitrator also (I renamed it from BiomassPoolFunctions) .
Sorry reply not finished but have to go.  Will finish tomorrow

2022-09-01 20:59 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Structures/UIStructures.cs
> +
The other point was that this class (NutrientDemandFunctions) is just a rename of the BiomassDemand class with no further changes so these public functions are used by most PMF models currently

2022-09-01 21:01 UTC, HamishBrownPFR commented on Models/PMF/Organs/RootZoneState.cs
Have renamed IStuffForRootShapeThing.  Have tried what you suggest but it causes a whole lot of errors and I have not been able to determine the cause.  
What is the reason for ZoneState not being a model?  Most other things are.

2022-09-23 02:19 UTC, HamishBrownPFR commented
retest this please jenkins

2022-09-23 02:59 UTC, HamishBrownPFR commented
@hol353 is there anything else needs doing prior to merging this one?

2022-11-17 03:09 UTC, hol353 approved these changes

2022-11-17 03:09 UTC, merged