7499 Manager Quirks
APSIMInitiative/ApsimX pull request #7923
Opened 2023-04-13 04:58 UTC by par456

Resolves #7499

The run button will now recompile all the scripts in the model before running the simulation. Will not run the simulation if a script has an error and will show script error.

A context menu option has been added for manager nodes, this allows you to compile the script without the page refreshing like when clicking a node or the run button. This should fix the undo problem and keeps the script tab open.

2023-04-14 03:38 UTC, hol353 requested changes

2023-04-14 03:38 UTC, hol353 commented on ApsimNG/Presenters/ManagerPresenter.cs
> +
Why doesn't manager set this flag when it tries to do a compile?

2023-04-14 03:38 UTC, hol353 commented on Models/Management/Manager.cs
>          /// <summary>
If manager sets this property then it can be made private set;

2023-04-14 03:38 UTC, hol353 commented on ApsimNG/Menus/MainMenu.cs
>                  Runner runner = new Runner(model, runType: Runner.RunTypeEnum.MultiThreaded, wait: false);
Instead of doing the above code in MainMenu.cs, the manager could throw the exception in it's 'OnStartOfSimulation' method. This method will be called whenever a simulation starts running.

2023-04-19 00:08 UTC, par456 commented on ApsimNG/Presenters/ManagerPresenter.cs
> +
That is a good point, I've moved the flag setting to the Manager.RebuildScriptModel() function where it should have been the first time. I've then reverted all changes to the ManagerPresenter.

2023-04-19 00:08 UTC, par456 commented on Models/Management/Manager.cs
>          /// <summary>
Made private now that manager handles the flags

2023-04-19 00:09 UTC, par456 commented on ApsimNG/Menus/MainMenu.cs
>                  Runner runner = new Runner(model, runType: Runner.RunTypeEnum.MultiThreaded, wait: false);
The exception is now thrown from the OnStartOfSimulation function.

2023-04-20 23:23 UTC, hol353 approved these changes

2023-04-20 23:23 UTC, merged