Added "Germination Temperature" to "GerminatiingPhase".
APSIMInitiative/ApsimX pull request #8536
Opened 2024-01-10 02:57 UTC by BrianCollinss

Resolves #8535 

If "Temperature" is a child of "GerminatingPhase", it will be used. Otherwise, it will be ignored.

2024-01-15 22:45 UTC, hol353 requested changes

2024-01-15 22:45 UTC, hol353 commented on Models/PMF/Phenology/Phases/GerminatingPhase.cs
> +        private ISoilTemperature soilTemperature = null;
There will always be a ISoilTemperature in every simulation. Doesn't need to be optional.

2024-01-15 22:45 UTC, hol353 commented on Models/PMF/Phenology/Phases/GerminatingPhase.cs
> +        private IFunction temperature = null;
We don't like optional functions because they obscure behaviour. If a developer is looking at GerminatingPhase in a model in the GUI, they won't see that GerminatingPhase can have a child temperature function. If you make it explicit and require all GerminatingPhase functions have a temperature function (even if it is a constant function set to 1) then it is obvious.

Remove the IsOptional and then write a converter that inserts a temperature function (constant function set to 1) into every GerminingPhase in every .apsimx file.

2024-01-15 22:45 UTC, hol353 commented on Models/PMF/Phenology/Phases/GerminatingPhase.cs
> +        public double GerminationTemperature { get { return temperature == null ? -999 : temperature.Value(); } }
If the temperature function isn't optional then there is no need for this property.

2024-01-15 22:45 UTC, hol353 commented on Models/PMF/Phenology/Phases/GerminatingPhase.cs
>              {
Refer to the temperature function directly rather than to the GerminationTemperature property.

2024-01-16 01:08 UTC, BrianCollinss commented
@hol353 would you please advise whether I must upgrade all recourses and commit/push again?

2024-01-16 02:01 UTC, hol353 commented
Yes you will need to upgrade all resources. There is a button on the home screen of the APSIM GUI that will do it for you. You can then commit the changed files and push to this PR.

2024-01-16 02:46 UTC, hol353 approved these changes

2024-01-16 02:47 UTC, merged