Simple crop models
APSIMInitiative/ApsimX pull request #8544
Opened 2024-01-15 02:12 UTC by HamishBrownPFR

this pull request contains the content originally put up on #8479.  I have closed that because the branch became cluttered with other work and put this up to reduce the amount of stuff contained in this PR to that originally intended.

Working on #8175 #7869 #7075 (suite of simple crop, tree and pasture models)

Added fRadnAllZones variable into ICanopy. This is the proportion of the total radiation over both zones that a crops in a specific zone is intercepting. We have been calculating this in manager scripts but seems safer to do it in Microclimate

Some harmonizing of approaches and functionality between SCRUM, STRUM and SPRUM

2024-01-15 03:27 UTC, HamishBrownPFR commented
@hol353 @par456 @ric394 

This is a tidy up of https://github.com/APSIMInitiative/ApsimX/pull/8479.  The comments on that had been responded to but the branch needed to be updated before it could be merged.  Unfortunately, I had committed so other stuff onto the same branch in the time that lapsed so could not update.  I have set up a clean branch and pull request.  This should be good to merge now.

If you are happy this is good to merge please do so.

2024-01-15 22:48 UTC, HamishBrownPFR commented
@hol353 could you take a look at this one when you have a min

2024-01-15 23:17 UTC, hol353 requested changes

2024-01-15 23:17 UTC, hol353 commented on Models/Interfaces/ICanopy.cs
> +        double fRadnAllZones { get; set; }
I don't like fRadnAllZones in ICanopy. None of the classes that implement ICanopy use this so it shouldn't be in the interface. MicroClimateZone sets it so I think it should be in here. MicroClimateZone could have a method to provide the value to a manager script for a given canopy. e.g.

```c#
Dictionary<ICanopy, double> fRadnAllZones;
public double FractionRadnAllZones(ICanopy canopy)
{
    return fRadnAllZones[canopy];
}
```

2024-01-15 23:17 UTC, hol353 commented on Models/PMF/SimplePlantModels/SprumPastureInstance.cs
> +        public Cultivar coeffCalc()
Method names start with upper case.

2024-01-15 23:17 UTC, hol353 commented on Models/PMF/SimplePlantModels/StrumTreeInstance.cs
> +        public bool RootThyNeighbour { get; set; }
Yeah, no. Very creative and very Hamish like but we need a better name.

2024-01-16 02:28 UTC, HamishBrownPFR commented on Models/Interfaces/ICanopy.cs
> +        double fRadnAllZones { get; set; }
This was a bit handy for reporting but the core reason why I added it I moved away from so it was no longer necessary.  I have removed this new variable from the current push

2024-01-16 02:28 UTC, HamishBrownPFR commented on Models/PMF/SimplePlantModels/SprumPastureInstance.cs
> +        public Cultivar coeffCalc()
changed in current push

2024-01-16 02:28 UTC, HamishBrownPFR commented on Models/PMF/SimplePlantModels/StrumTreeInstance.cs
> +        public bool RootThyNeighbour { get; set; }
Changed in current push

2024-01-16 02:53 UTC, hol353 commented
This branch (HamishBrownPFR/SimpleCropModels) doesn't seem to have fRadnAllZones  removed but I notice your PFR/SimpleCropModels branch does. Do you need to pull from PFR/SimpleCropModels?

2024-01-16 03:00 UTC, HamishBrownPFR commented
Thanks Dean.  To many branches.  Hoping to get some closed soon.

2024-01-16 04:01 UTC, hol353 requested changes

2024-01-16 04:01 UTC, hol353 commented on Models/Surface/SurfOrganicMatterType.cs
> +        public double fRadnAllZones { get; set; }
Remove this one as well.

2024-01-16 19:31 UTC, HamishBrownPFR commented on Models/PMF/Organs/SimpleLeaf.cs
> +        public double fRadnAllZones { get; set; }
I thought I had.  Done now

2024-01-16 19:31 UTC, HamishBrownPFR commented on Models/Surface/SurfOrganicMatterType.cs
> +        public double fRadnAllZones { get; set; }
Dito, there were a couple of others too.

2024-01-16 23:14 UTC, hol353 approved these changes

2024-01-16 23:14 UTC, merged