Water Presenter 'Fill from top?' checkbox bug fix
APSIMInitiative/ApsimX pull request #8613
Opened 2024-02-06 06:17 UTC by ric394

resolves #8543

2024-02-07 22:58 UTC, par456 commented
Can you add some units tests in for this to check that when these parameters are updated in water, it actually updates the related numbers correctly.

2024-02-19 06:29 UTC, ric394 commented
retest this please jenkins

2024-02-21 04:03 UTC, hol353 commented
I've pulled this branch and it works well. Two things I noticed. 

1. Percent full should be allowed to go above 100%.
2. Initial values in the grid should be able to go to SAT. Currently they are bound to DUL.
3. If you try to enter a percent full of 101% then the error below is given. It should say 'Invalid value for percent full: 101. Must be between [0, 100]'

![image](https://github.com/APSIMInitiative/ApsimX/assets/1943827/93990c9b-3c6e-48a0-a2c0-092099967313)

2024-02-21 04:08 UTC, hol353 requested changes

2024-02-21 04:08 UTC, hol353 commented on APSIM.Shared/Utilities/DataTableUtilities.cs
> +            //else values = new double[numValues - startRow];
Remove commented code.

2024-02-21 04:08 UTC, hol353 commented on APSIM.Shared/Utilities/DataTableUtilities.cs
>              {
Likewise, more commented code. Also loop variables (e.g. Row) should start with a lower case.

2024-02-21 04:08 UTC, hol353 commented on APSIM.Shared/Utilities/DataTableUtilities.cs
>                          values[index] = Convert.ToDouble(table.Rows[Row][columnName], culture);
Commented code.

2024-02-21 04:08 UTC, hol353 commented on APSIM.Shared/Utilities/DataTableUtilities.cs
> +        }
Couldn't this just be:

```c#
return Double.TryParse(table.Rows[0][0] as string, out double firstValue)
```

2024-02-21 04:14 UTC, par456 commented
Ah yeah, I had some questions about that as well.

How does the graph need to fill when going above 100% if filled from top or not?

Obviously when filled from top is off, it can just continue to evenly fill from LL, that's fine. But when filled from top is on, does it fill all the way to SAT before filling the next layer, or does it fill up to DUL until all layers are filled to DUL, then start filling to SAT for each layer as it goes higher?

Currently as well, the percentage filled is based on DUL, so at 100% DUL is saturated, should 200% be SAT saturated, or should it just be whatever percentage it takes to fill to SAT.

Also, are the initial values limited to SAT? So if someone puts in 1000% we can cap off the initial values to SAT.

2024-02-21 04:39 UTC, hol353 commented
Up to 100% full it should use DUL. Once above 100%, filled from top should fill to SAT.

> Currently as well, the percentage filled is based on DUL, so at 100% DUL is saturated, should 200% be SAT saturated, or should it just be whatever percentage it takes to fill to SAT.

It should be whatever percentage it takes to fill to SAT. Will be different percent for different soils.

> Also, are the initial values limited to SAT? So if someone puts in 1000% we can cap off the initial values to SAT.

Yes, always cap it to SAT.

2024-03-06 05:21 UTC, par456 commented
Looks it's finally run green on Jenkins. Should be good for a review @hol353 and hopefully merged.

2024-03-06 21:41 UTC, hol353 approved these changes

2024-03-06 21:41 UTC, hol353 commented
Good job @ric394! I've pulled the branch and had a play. Can't find any further problems. Merging...

2024-03-06 21:41 UTC, merged