Cleanup met files
APSIMInitiative/ApsimX pull request #8765
Opened 2024-03-19 05:00 UTC by ric394

resolves #6863 

1. Renames met files with country code and place name.
2. Adds converter.
3. Resource files updated to 172

2024-03-19 06:50 UTC, par456 requested changes

2024-03-19 06:50 UTC, par456 commented on .vscode/launch.json
can you pull this one out of this PR

2024-03-19 06:50 UTC, par456 commented on ApsimNG/ApsimNG.csproj
can you pull this one out of this PR

2024-03-20 22:46 UTC, ric394 commented on .vscode/launch.json
I've updated the PR so they are the same, this shouldn't cause and issue. Tell me if this not adequate.

2024-03-20 22:46 UTC, ric394 commented on ApsimNG/ApsimNG.csproj
I've updated the PR so they are the same, this shouldn't cause and issue. Tell me if this not adequate.

2024-03-21 00:23 UTC, par456 commented on Models/Core/ApsimFile/Converter.cs
Git has buggered this file up. Grab your function out, reset the file, and your function back in again.

Also, the filename part just needs to be more specific, add "/Examples/WeatherFiles/" to the start of each thing you search for and replace.

2024-03-21 00:23 UTC, par456 commented on ApsimNG/Resources/TreeViewImages/ObservedReport.svg
Why is this in here?

2024-03-21 23:14 UTC, par456 approved these changes

2024-03-21 23:15 UTC, merged