8819 Root Growth Changes
APSIMInitiative/ApsimX pull request #8831
Opened 2024-04-10 23:51 UTC by par456

working on #8819

2024-04-15 22:36 UTC, hol353 requested changes

2024-04-15 22:36 UTC, hol353 commented on Models/Functions/SoilWaterScale.cs
> +        public string SATModel { get; set; } = "[Physical].SAT";
Why do we need to let the user specify a SATModel? I can't think of a use case.

2024-04-15 22:36 UTC, hol353 commented on Models/Functions/SoilWaterScale.cs
> +        public string DULModel { get; set; } = "[Physical].DUL";
As above, why do we need this?

2024-04-15 22:36 UTC, hol353 commented on Models/Functions/SoilWaterScale.cs
> +                lls = Locator.Get(LLModel) as double[];
Locator.Get is slow at runtime. Move the call to StartOfSimulation. No need to do it everyday of the sim.

2024-04-15 22:36 UTC, hol353 commented on Models/Functions/SoilWaterScale.cs
> +        public string LLModel { get; set; } = "[Physical].LL15";
This one makes sense. The use case is the user wants to specify one of airdry, ll15, crop ll. Rather than a string I wonder about using an enum instead. That way the user gets a drop down rather than free form text.

2024-04-15 22:36 UTC, hol353 commented on Models/PMF/Organs/Root.cs
> -        private SoilCrop soilCrop;
Why has soilCrop been made a public property of Root?

2024-04-15 23:17 UTC, par456 commented on Models/PMF/Organs/Root.cs
> -        private SoilCrop soilCrop;
That was to avoid copying the name matching code over to SoilWaterScale, as Root already has a reference to the SoilCrop.

If there is another place a reference to SoilCrop is available, I'm happy to use that, I just don't want to do the same string name matching again in SoilWaterScale.

2024-04-15 23:17 UTC, par456 commented on Models/Functions/SoilWaterScale.cs
> +        public string LLModel { get; set; } = "[Physical].LL15";
I like that idea better, it'll make it easier to use, will change to enum.

2024-04-16 02:28 UTC, hol353 commented on Models/PMF/Organs/Root.cs
> -        private SoilCrop soilCrop;
Ok that makes sense. Leave it as it is.

2024-04-17 02:56 UTC, par456 commented
Should be right to merge now.

2024-04-17 20:51 UTC, hol353 approved these changes

2024-04-17 20:51 UTC, merged