Soil carbon spin-up tutorial
APSIMInitiative/ApsimX pull request #8952
Opened 2024-05-20 23:20 UTC by sno036

resolves #8951

2024-05-21 06:06 UTC, ric394 requested changes

2024-05-21 06:06 UTC, ric394 commented on Examples/Tutorials/InitialisingSoilCarbonPools.apsimx
> +          "FileName": "C:\\aaUnderVC\\ApsimX\\Examples\\WeatherFiles\\NZ_Lincoln.met",
This needs to use : `"%root%/Examples/WeatherFiles/NZ_Lincoln.met",` like line 55

2024-07-29 02:42 UTC, hol353 commented
@ric394 I've made your suggested fix. This is now ready.

2024-07-29 02:46 UTC, ric394 approved these changes

2024-07-29 02:46 UTC, merged