Progress with testing arbitrator
APSIMInitiative/ApsimX pull request #9025
Opened 2024-06-14 23:18 UTC by HamishBrownPFR

Working on #6763

2024-06-16 22:01 UTC, HamishBrownPFR commented
@hol353 @par456 can ypu please review and merge if happy.  Code changes to the new arbitrator so should not be affecting anything in release

2024-06-16 23:56 UTC, hol353 requested changes

2024-06-16 23:56 UTC, hol353 commented on Models/PMF/Biomass/Biomass.cs
> +        public Biomass(OrganNutrientsState ons)
By including this here, the Biomass class knows about OrganNutirentState. This doesn't feel right. Instead, have a method in OrganNutirentState called something like ToBiomass that creates an Biomass instance.

2024-06-16 23:56 UTC, hol353 commented on Models/PMF/BiomassArbitration/BiomassArbitrator.cs
> +
These sorts of property gets can be simplified like this:
```c#
public double TotalCFixationSupply => Carbon.TotalFixationSupply;
```

2024-06-16 23:56 UTC, hol353 commented on Models/PMF/BiomassArbitration/BiomassArbitrator.cs
> +                if (cdiff > 1e-12)
Don't we have a MathUtilities function that does this?

2024-06-16 23:56 UTC, hol353 commented on Models/PMF/BiomassArbitration/Functions/DeficitDemandFunction.cs
> +        //private OrganNutrientDelta dNitrogen = null;
Why is the variable called dNutrient? What does the 'd' stand for? Also remove commented code.

2024-06-16 23:56 UTC, hol353 commented on Models/PMF/BiomassArbitration/Functions/DeficitDemandFunction.cs
> +            if ((model is OrganNutrientDelta)||(model is Organ) || (model is IPlant) || (model is IZone) || (model is Simulation))
Yuk. This looks terrible. Is there a better way to find a pool? I'm not sure how this is supposed to work but do pools have an interface that you can look for with a FindInScope call?

2024-06-16 23:56 UTC, hol353 commented on Models/PMF/BiomassArbitration/Functions/MobilisationSupplyFunction.cs
> +            double reAllocationsupply = sourceAmount * multiplier * parentOrgan.theSenescenceRate;
Remove the 'the' prefix.

2024-06-16 23:56 UTC, hol353 commented on Models/PMF/BiomassArbitration/RootNetwork.cs
> +            set { PlantZone.Depth = value; }
Is a setter needed? What would call it?

2024-06-16 23:56 UTC, hol353 commented on Models/PMF/BiomassArbitration/Structures/IParentOfNutrientsPoolState.cs
>      public interface IParentOfNutrientsPoolState
Is this still needed?

2024-06-16 23:56 UTC, hol353 commented on Models/PMF/BiomassArbitration/Structures/OrganNutrientsState.cs
> +                return Cconc > 0 ? Carbon / Cconc : new NutrientPoolsState(0, 0, 0);
These can all be simplified as per earlier comment.

2024-06-16 23:56 UTC, hol353 commented on Models/PMF/BiomassArbitration/Structures/OrganNutrientsState.cs
> +        public static OrganNutrientsState divide (OrganNutrientsState a, double b, double cconc)
These should be upper case.

2024-06-17 00:30 UTC, HamishBrownPFR commented on Models/PMF/Biomass/Biomass.cs
> +        public Biomass(OrganNutrientsState ons)
Change made as suggested.

2024-06-17 00:32 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/BiomassArbitrator.cs
> +
Change made

2024-06-17 00:39 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/BiomassArbitrator.cs
> +                if (cdiff > 1e-12)
Yes, FloatsAreEquat.  Thanks

2024-06-17 00:42 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Functions/DeficitDemandFunction.cs
> +        //private OrganNutrientDelta dNitrogen = null;
stands for delta.  Have changed variable name to organNutrientDelta to be clearer

2024-06-17 01:48 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Functions/DeficitDemandFunction.cs
> +            if ((model is OrganNutrientDelta)||(model is Organ) || (model is IPlant) || (model is IZone) || (model is Simulation))
This was more complex than needed.  Have reduced it to a name check to throw an error if name is not in required list.

2024-06-17 01:51 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Functions/MobilisationSupplyFunction.cs
> +            double reAllocationsupply = sourceAmount * multiplier * parentOrgan.theSenescenceRate;
Done

2024-06-17 01:58 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Structures/OrganNutrientsState.cs
> +                return Cconc > 0 ? Carbon / Cconc : new NutrientPoolsState(0, 0, 0);
done

2024-06-17 02:00 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Structures/OrganNutrientsState.cs
> +        public static OrganNutrientsState divide (OrganNutrientsState a, double b, double cconc)
Fixed.  I wonder why they were working?

2024-06-17 02:05 UTC, HamishBrownPFR commented on Models/PMF/BiomassArbitration/Structures/IParentOfNutrientsPoolState.cs
>      public interface IParentOfNutrientsPoolState
No, Removed

2024-06-17 03:15 UTC, HamishBrownPFR commented
@hol353 requested changes made.  Thanks

2024-06-17 04:00 UTC, hol353 approved these changes

2024-06-17 04:00 UTC, merged