Deropapy
APSIMInitiative/ApsimX pull request #9103
Opened 2024-07-03 03:51 UTC by HamishBrownPFR

working on #8551

2024-07-03 05:43 UTC, HamishBrownPFR commented
@hol353 @par456 @ric394 please review

2024-07-03 21:10 UTC, hol353 requested changes

2024-07-03 21:10 UTC, hol353 commented on Models/PMF/SimplePlantModels/DEROPAPY.cs
> +        private Organ Leaf = null;
Privates start with a lower case.

2024-07-03 21:10 UTC, hol353 commented on Models/PMF/SimplePlantModels/DEROPAPY.cs
>          {
DataTableUtilities.DataTableToText method writes a DataTable to a .csv file.

2024-07-04 01:11 UTC, HamishBrownPFR commented on Models/PMF/SimplePlantModels/DEROPAPY.cs
> +        private Organ Leaf = null;
changed

2024-07-04 01:14 UTC, HamishBrownPFR commented on Models/PMF/SimplePlantModels/DEROPAPY.cs
>          {
Thanks, thats a nicer way of doing it.  I have commented the CSV writing out at the moment because the grid display adds a blank line below the header which mucks thing up.  Also occasionally hit problems where it doesn't read anything and the overwrites the .csv file with the blank datatable so need to add a test to make sure the datatable is the same size and shape as the original before it writes.

2024-07-04 02:35 UTC, HamishBrownPFR commented
Should be good to go now @hol353

2024-07-04 02:44 UTC, hol353 commented on Models/PMF/SimplePlantModels/DEROPAPY.cs
> +            bool RootThyNeighbour = bool.Parse(CurrentCropParams["RootTheNeighboursZone"]);
This one almost slipped through. Please choose another variable name.

2024-07-05 10:39 UTC, HamishBrownPFR commented on Models/PMF/SimplePlantModels/DEROPAPY.cs
> +            bool RootThyNeighbour = bool.Parse(CurrentCropParams["RootTheNeighboursZone"]);
changed

2024-07-05 10:39 UTC, HamishBrownPFR commented
@hol353 please merge

2024-07-07 21:11 UTC, merged