9137 Soil Download Issue
APSIMInitiative/ApsimX pull request #9161
Opened 2024-07-17 01:31 UTC by par456

Resolves #9137 

Changed to https for apsoil requests, also did some checking for other bugs encountered when testing.

2024-07-18 00:18 UTC, hol353 requested changes

2024-07-18 00:18 UTC, hol353 commented on ApsimNG/Presenters/SoilDownloadPresenter.cs
> +                catch (Exception e)
Rather then using try / catch to determine if a string can be converted to double, use ```double.TryParse``` method

2024-07-18 01:43 UTC, par456 commented on ApsimNG/Presenters/SoilDownloadPresenter.cs
> +                catch (Exception e)
Yep, that's a better idea, updated.

2024-07-19 00:46 UTC, hol353 commented on ApsimNG/Presenters/SoilDownloadPresenter.cs
> +                if(!canParse) {
This can be combined onto one line like this:
```c#
if (!double.TryParse(latitudeEditBox.Text, out double latitude)
```

Simpler?

2024-07-19 01:27 UTC, par456 commented on ApsimNG/Presenters/SoilDownloadPresenter.cs
> +                if(!canParse) {
yes, yes it can.

2024-07-19 02:31 UTC, hol353 approved these changes

2024-07-19 02:32 UTC, merged